export const GET_MY_PLACE_DETAIL = "GET_MY_PLACE_DETAIL";
export const GET_ALL_PLACE = "GET_ALL_PLACE";
export const POST_PREFERENCE = "POST_PREFERENCE";
export const DELETE_PREFERENCE = "DELETE_PREFERENCE";
export const SAVE_PREFERENCE = "SAVE_PREFERENCE";
export const SAVE_RECOMMENDATION = "SAVE_RECOMMENDATION";